# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lL0Hp--WEtAuvwVOa59ernudFo58Lzi6
"""

from scipy.stats import expon
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
dx=0.005
x=np.arange(4.5,100,dx)
y1=(1/3)*(np.exp(-(x/3)))
y2=0.2*(np.exp(-(x/5)))
cdf1=np.cumsum(y1*dx)
cdf2=np.cumsum(y2*dx)
plt.plot(x,y1,label="pdf")
plt.plot(x,cdf1,label="cdf")
plt.xlabel("X")
plt.ylabel("Probability Values")
plt.title("CDF for exponential distribution when lambda=3")
plt.legend()
plt.show()
plt.savefig('1.png')

plt.plot(x,y2,label="pdf")
plt.plot(x,cdf2,label="cdf")
plt.xlabel("X")
plt.ylabel("Probability Values")
plt.title("CDF for exponential distribution when lambda=5")
plt.legend()
plt.show()

