# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16eixBFWbeJVrQe6YZqBQR1u1d1CY5Zy4
"""

import random 
def roll(event):
  count=0
  testcases=100000
  for i in range(1,testcases):
    throw_1=random.randint(1,6)
    throw_2=random.randint(1,6)
    #A is the event that sum of 6 has occured when a die is rolled twice
    #B is the event that a 4 has occured atleast once when a die is rolled twice
    #AB is the evn=ent that a sum of 6 has occured with atleast one four when a die is rolled twice
    if event=='A':
      if throw_1+throw_2==6:
        count=count+1

    if event=='AB':
      if throw_1+throw_2==6:
        if throw_1==4 or throw_2==4:
          count=count+1
  return count/testcases
  #using conditional probability to find the probability of B given A has occured
sim_prob=roll('AB')/roll('A')
print("The experimental probability of getting a sum 6 when a die is rolled twice is ",roll('A'))
print("The experimental probability of getting a 4 atleast once and sum of 6 when die is rolled twice is ",roll('AB'))
print("The experimental probability of getting a 4 given that the sum is 6 when a die is rolled twice is ",sim_prob)
err_1=abs(roll('A')-(5/36))
err_2=abs(roll('AB')-(2/36))
err=abs(sim_prob-0.4)
print("The absolute error in calculated and simulated probabilty of event A is ",err_1)
print("The absolute error in calculated and simulated probabilty of event AB is ",err_2)
print("The absolute error in calculated and simulated probabilty of event B given A has occured is ",err)